### PR TITLE
Added Exportable concern

### PR DESCRIPTION
**Pull request by QuibaX**

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Can add it to te example, but it's not necessary to have the Exportable trait. Only if you want to use the convenience methods. In the current example, it's not needed to have the trait.

**Comment by QuibaX** [comment]
True, just because the FromCollection and FromQuery examples have the trait, and this one is pretty much the same style. Had to search for a second so thought i'd suggest.

**Comment by GlennM** [comment]
@QuibaX What's your opinion about it? Are you willing to update the PR to include the suggestion made by @patrickbrouwers ?

If so, please target it to the 3.1 version of the docs, as that's the most recent version which is maintained actively.

**Comment by GlennM** [comment]
@QuibaX Do you have any updates on this or shall we close the PR?

**Pull request closed without merging**
