### PR TITLE
Update multiple-sheets.md

### PR DESCRIPTION
**Pull request by chinleung**
Fixed the download example.

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Hey, thanks for your contribution. Can you explain the change? The example is correct.

**Comment by chinleung** [comment]
The `InvoicesExport` has no `download` method no?

**Comment by patrickbrouwers** [comment]
It does because of the `use Exportable;` in the `InvoicesExport` example

**Comment by chinleung** [comment]
Oh my bad I missed the `Exportable`! 🙃

**Comment by patrickbrouwers** [comment]
No worries :)

**Pull request closed without merging**
